{
    'name': 'Farming Management',
    'version': '17.0.1.0',
    'category': 'Farming Agriculture',
    'author': 'Aditya',
    'summary': 'Comprehensive management solution for agriculture and farming.',
    'description': "Farming Management",
    'depends': ['base', 'stock'],
    'data': [
        'security/ir.model.access.csv',
        'views/farm_views.xml',
        'views/crop_views.xml', 
        'views/equipment_views.xml',
        'views/res_users_views.xml',
        'views/bom_views.xml',
        'views/crop_analysis_views.xml', 
        'reports/crop_reports.xml',      
        'views/crop_report_template.xml',
        'data/initial_data.xml',
    ],
    'images': ['static/description/farming.png'], 
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'price': 50,
    'currency': 'USD',
}
