{
    'name': 'Approval Tiered',
    'version': '17.0.1.0',
    'category': 'Tech',
    'author': '',
    'summary': '',
    'description': "Tiering Approvals",
    'depends': ['purchase','purchase_request', 'mail'],
    'data': [
        'data/ir_config_parameter_data.xml',
        'security/groups.xml',
        'security/ir.model.access.csv',
        'views/purchase_request_views.xml',
        'views/res_config_settings.xml',
        'views/purchase_signature_wizard_views.xml',
        'views/purchase_signature_wizard_views second.xml',
        'report/report_purchase_request.xml',
    ],
    'images': ['static/description/farming.png'], 
    'installable': True,
    'application': True,
    'license': 'LGPL-3',
    'price': 50,
    'currency': 'USD',
}
